In [8]:

import torch

B, T = 4, 3
device = "cuda"
vocab_size = 100
indices = torch.randint(0, 99, (B, T)).to(device)
labels = torch.randint(0, 3, (B,)).to(device)

t = torch.rand(indices.shape[0], device=device)

# Create binary mask based on timestep t
mask = torch.bernoulli(t.unsqueeze(1).expand(-1, indices.shape[1])).bool()


In [9]:
mask

tensor([[False, False, False],
        [False,  True, False],
        [False,  True,  True],
        [ True,  True,  True]], device='cuda:0')

In [10]:

# Create corrupted version by cloning original indices
corrupted = indices.clone()
corrupted_as_null = indices.clone()
corrupted_as_null[mask] = vocab_size - 1


In [11]:
indices, corrupted_as_null

(tensor([[29, 68,  9],
         [58, 90, 73],
         [93, 33, 89],
         [89, 50, 29]], device='cuda:0'),
 tensor([[29, 68,  9],
         [58, 99, 73],
         [93, 99, 99],
         [99, 99, 99]], device='cuda:0'))

In [12]:

# Only corrupt tokens where mask is True
# Sample random tokens from vocab range for corrupted positions
num_masked = mask.sum().item()
if num_masked > 0:
    corrupted[mask] = torch.randint(
        0, vocab_size - 1, (num_masked,), device=device
    )
    
corrupted

tensor([[29, 68,  9],
        [58, 41, 73],
        [93, 51, 98],
        [ 5, 35, 44]], device='cuda:0')